version: '3.8'
services:
  db:
    # Мы берем не просто postgres, а уже готовую сборку с TimescaleDB
    image: timescale/timescaledb:latest-pg15
    container_name: stridex_db
    restart: always
    environment:
      - POSTGRES_USER=stridex_admin
      - POSTGRES_PASSWORD=secure_password
      - POSTGRES_DB=stridex_main
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: