
services:
  db:
    image: timescale/timescaledb:latest-pg15
    container_name: stridex_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ayaulym^2011
      - POSTGRES_DB=stridex
    ports:
      - "5433:5432"
    volumes:
      - stridex_db:/var/lib/postgresql/data

volumes:
  stridex_db: